function ultrasoundApp()
%ULTRASOUNDAPP Breast ultrasound classification using ResNet-18.

    %% ============================================================
    %  Load final ResNet-18 model
    %  ============================================================

    modelPath = ...
        "C:\Users\anura\Desktop\RealTimeMedicalImaging\models\netResNet.mat";

    modelData = load(modelPath, "netResNet");
    netResNet = modelData.netResNet;

    % Get class names directly from the trained network
    classNames = string(netResNet.Layers(end).Classes);

    %% ============================================================
    %  Main Window
    %  ============================================================

    fig = uifigure( ...
        "Name", "Breast Ultrasound Intelligence — ResNet-18", ...
        "Position", [100 80 1150 720], ...
        "Color", [0.08 0.09 0.11]);

    %% ============================================================
    %  Header
    %  ============================================================

    header = uipanel(fig, ...
        "Position", [0 650 1150 70], ...
        "BackgroundColor", [0.10 0.12 0.15], ...
        "BorderType", "none");

    uilabel(header, ...
        "Text", "BREAST ULTRASOUND INTELLIGENCE", ...
        "Position", [35 30 600 28], ...
        "FontSize", 20, ...
        "FontWeight", "bold", ...
        "FontColor", [0.95 0.97 1.00]);

    uilabel(header, ...
        "Text", "ResNet-18 Deep Learning Classification System", ...
        "Position", [37 8 500 20], ...
        "FontSize", 11, ...
        "FontColor", [0.60 0.65 0.72]);

    %% ============================================================
    %  Image Panel
    %  ============================================================

    imagePanel = uipanel(fig, ...
        "Title", "  ULTRASOUND IMAGE  ", ...
        "Position", [35 105 680 520], ...
        "BackgroundColor", [0.11 0.12 0.14], ...
        "ForegroundColor", [0.80 0.84 0.90], ...
        "FontSize", 12, ...
        "FontWeight", "bold");

    ax = uiaxes(imagePanel, ...
        "Position", [20 55 640 420], ...
        "BackgroundColor", [0.05 0.05 0.06]);

    ax.XTick = [];
    ax.YTick = [];
    ax.XColor = "none";
    ax.YColor = "none";

    title(ax, ...
        "No ultrasound image selected", ...
        "Color", [0.65 0.68 0.74], ...
        "FontSize", 14);

    %% ============================================================
    %  Result Panel
    %  ============================================================

    resultPanel = uipanel(fig, ...
        "Title", "  ANALYSIS RESULT  ", ...
        "Position", [740 300 375 325], ...
        "BackgroundColor", [0.11 0.12 0.14], ...
        "ForegroundColor", [0.80 0.84 0.90], ...
        "FontSize", 12, ...
        "FontWeight", "bold");

    %% Prediction

    resultLabel = uilabel(resultPanel, ...
        "Text", "Awaiting Analysis", ...
        "Position", [35 220 305 45], ...
        "FontSize", 22, ...
        "FontWeight", "bold", ...
        "FontColor", [0.80 0.84 0.90], ...
        "HorizontalAlignment", "center");

    %% Confidence

    confidenceLabel = uilabel(resultPanel, ...
        "Text", "Model confidence: --", ...
        "Position", [35 190 305 25], ...
        "FontSize", 12, ...
        "FontColor", [0.60 0.65 0.72], ...
        "HorizontalAlignment", "center");

    %% Scores heading

    uilabel(resultPanel, ...
        "Text", "CLASSIFICATION SCORES", ...
        "Position", [35 155 305 22], ...
        "FontSize", 10, ...
        "FontWeight", "bold", ...
        "FontColor", [0.55 0.60 0.68], ...
        "HorizontalAlignment", "center");

    %% Class scores

    benignLabel = uilabel(resultPanel, ...
        "Text", "Benign       --", ...
        "Position", [55 115 265 28], ...
        "FontSize", 14, ...
        "FontColor", [0.85 0.87 0.92]);

    malignantLabel = uilabel(resultPanel, ...
        "Text", "Malignant    --", ...
        "Position", [55 78 265 28], ...
        "FontSize", 14, ...
        "FontColor", [0.85 0.87 0.92]);

    normalLabel = uilabel(resultPanel, ...
        "Text", "Normal       --", ...
        "Position", [55 41 265 28], ...
        "FontSize", 14, ...
        "FontColor", [0.85 0.87 0.92]);

    %% ============================================================
    %  Control Panel
    %  ============================================================

    controlPanel = uipanel(fig, ...
        "Title", "  IMAGE ANALYSIS  ", ...
        "Position", [740 105 375 170], ...
        "BackgroundColor", [0.11 0.12 0.14], ...
        "ForegroundColor", [0.80 0.84 0.90], ...
        "FontSize", 12, ...
        "FontWeight", "bold");

    selectButton = uibutton(controlPanel, ...
        "Text", "SELECT ULTRASOUND IMAGE", ...
        "Position", [50 75 275 48], ...
        "FontSize", 14, ...
        "FontWeight", "bold", ...
        "BackgroundColor", [0.12 0.45 0.75], ...
        "FontColor", [1 1 1], ...
        "ButtonPushedFcn", @selectImage);

    statusLabel = uilabel(controlPanel, ...
        "Text", "Ready — select an ultrasound image", ...
        "Position", [30 25 315 25], ...
        "FontSize", 11, ...
        "FontColor", [0.60 0.65 0.72], ...
        "HorizontalAlignment", "center");

    %% ============================================================
    %  Footer
    %  ============================================================

    uilabel(fig, ...
        "Text", ...
        "Model: ResNet-18   |   Input: 224 × 224 × 3   |   Classes: Benign • Malignant • Normal", ...
        "Position", [35 65 1080 22], ...
        "FontSize", 10, ...
        "FontColor", [0.45 0.49 0.56], ...
        "HorizontalAlignment", "center");


    %% ============================================================
    %  Image Selection + ResNet-18 Prediction
    %  ============================================================

    function selectImage(~, ~)

        [fileName, filePath] = uigetfile( ...
            {'*.png;*.jpg;*.jpeg', ...
             'Ultrasound Images (*.png, *.jpg, *.jpeg)'}, ...
            "Select Ultrasound Image");

        if isequal(fileName, 0)

            statusLabel.Text = "No image selected";
            return;

        end

        imagePath = fullfile(filePath, fileName);

        try

            %% ----------------------------------------------------
            % Read and display original image
            % -----------------------------------------------------

            originalImage = imread(imagePath);

            imshow(originalImage, "Parent", ax);

            title(ax, ...
                "Input Ultrasound", ...
                "Color", [0.85 0.88 0.94], ...
                "FontSize", 14, ...
                "FontWeight", "bold");

            %% ----------------------------------------------------
            % Start analysis
            % -----------------------------------------------------

            statusLabel.Text = "Analyzing with ResNet-18...";
            drawnow;

            %% ----------------------------------------------------
            % Run final ResNet-18 inference
            % -----------------------------------------------------

            [predictedLabel, confidence, scores, inferenceTime] = ...
                predictUltrasoundResNet(imagePath, netResNet);

            %% ----------------------------------------------------
            % Determine predicted class
            % -----------------------------------------------------

            predictedIndex = find( ...
                classNames == string(predictedLabel), 1);

            if isempty(predictedIndex)

                predictedIndex = 1;

            end

            %% ----------------------------------------------------
            % Update prediction
            % -----------------------------------------------------

            resultLabel.Text = ...
                "Prediction: " + upper(string(predictedLabel));

            confidenceLabel.Text = ...
                sprintf("Model confidence: %.2f%%", ...
                confidence * 100);

            %% ----------------------------------------------------
            % Update scores
            % -----------------------------------------------------

            for k = 1:numel(classNames)

                currentClass = lower(classNames(k));
                currentScore = scores(k) * 100;

                switch currentClass

                    case "benign"

                        benignLabel.Text = ...
                            sprintf("Benign       %6.2f%%", ...
                            currentScore);

                    case "malignant"

                        malignantLabel.Text = ...
                            sprintf("Malignant    %6.2f%%", ...
                            currentScore);

                    case "normal"

                        normalLabel.Text = ...
                            sprintf("Normal       %6.2f%%", ...
                            currentScore);

                end

            end

            %% ----------------------------------------------------
            % Result color
            % -----------------------------------------------------

            switch lower(string(predictedLabel))

                case "benign"

                    resultLabel.FontColor = ...
                        [0.35 0.85 0.60];

                case "malignant"

                    resultLabel.FontColor = ...
                        [0.95 0.40 0.40];

                case "normal"

                    resultLabel.FontColor = ...
                        [0.40 0.75 0.95];

                otherwise

                    resultLabel.FontColor = ...
                        [0.85 0.87 0.92];

            end

            %% ----------------------------------------------------
            % Status
            % -----------------------------------------------------

            statusLabel.Text = sprintf( ...
                "Analysis complete — %.4f s inference", ...
                inferenceTime);

        catch ME

            statusLabel.Text = ...
                "Error during analysis";

            uialert(fig, ...
                ME.message, ...
                "ResNet-18 Prediction Error");

        end

    end

end