function layers = createCNN(classNames, classWeights)
%CREATECNN Create a lightweight CNN for BUSI classification.

    numClasses = numel(classNames);

    layers = [
        imageInputLayer([224 224 1], ...
            Normalization="none", ...
            Name="input")

        convolution2dLayer(3,16, ...
            Padding="same", ...
            Name="conv1")
        batchNormalizationLayer(Name="bn1")
        reluLayer(Name="relu1")
        maxPooling2dLayer(2, ...
            Stride=2, ...
            Name="pool1")

        convolution2dLayer(3,32, ...
            Padding="same", ...
            Name="conv2")
        batchNormalizationLayer(Name="bn2")
        reluLayer(Name="relu2")
        maxPooling2dLayer(2, ...
            Stride=2, ...
            Name="pool2")

        convolution2dLayer(3,64, ...
            Padding="same", ...
            Name="conv3")
        batchNormalizationLayer(Name="bn3")
        reluLayer(Name="relu3")
        maxPooling2dLayer(2, ...
            Stride=2, ...
            Name="pool3")

        dropoutLayer(0.30,Name="dropout")

        globalAveragePooling2dLayer(Name="gap")

        fullyConnectedLayer(numClasses,Name="fc")
        softmaxLayer(Name="softmax")

        classificationLayer( ...
            Classes=classNames, ...
            ClassWeights=classWeights, ...
            Name="output")
    ];

end